name: tvets_collegechecker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase: ^2.2.7  # Upgrade to the latest compatible version
  flutter_dotenv: ^5.0.2
  postgrest: ^2.1.3  # Keep the required version
  provider: ^6.0.3


  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/.env
